### ISSUE TITLE
有关NTU-RGB-D数据集下载的问题

### ISSUE THREAD

**Issue by tian984** [zhy0860/phi#2]
您好，请问您的NTU RGB+D数据集能重新分享一下吗，因为Google云盘拒绝访问。还要请教您一个问题，第二个数据集Kinetics+NTU的组织结构是什么样的呢？期待您的回复。

**Comment by zhy0860** [comment]
您好，google云盘下面的百度网盘链接是可以用的，请通过该链接和提取码来下载NTU RGB+D和Kinetics数据集。Kinetics+NTU指的是百度网盘链接下NTU RGB+D和Kinetics这两个数据集都有，其中Kinetics是2D骨骼数据，NTU RGB+D是3D骨骼数据，具体结构可以分别从两个数据集的官网进一步了解。

**Comment by tian984** [comment]
感谢您的回复，百度云盘的数据集下载之后，需要向您请教如下问题：
1、code中的数据集路径，除去绝对路径，相对路径datasets中的ntu112，ntu_cv和ntu_cs文件夹以及其目录下的train.txt、test.txt文件在您所给的数据集中均未找到，不知您使用的是否是处理后的数据集，如果是的话烦请您告知一下文件的组织结构，非常感谢！
2、Kinetics400数据集报错： No such file or directory: '/home/tzz/datasets/Kinetics400/train/uvoBn-8AxHI.mat'，请问这个MAT文件如何获取呢？

**Comment by zhy0860** [comment]
您好，我们之前是将原始的.skeleton格式数据用matlab处理成的.mat文件读取的，不够方便，现在已经统一采用2s-AGCN的代码将原始数据处理成.npy格式，请参考https://github.com/lshiwjx/2s-AGCN 中的data_gen部分代码，dataloader部分的改动也可参考其代码。数据格式：因为显卡内存限制，将NTU原始数据统一采样为112帧 X 50（两个人的骨骼点合并到一个维度）X 3（x，y，z三通道）。Kinetics原始数据处理为112帧 X 36（两个人的骨骼点合并到一个维度）X 2（x，y二通道）。为方便您调试ntu60的.mat格式文件已上传百度网盘，文件名ntu112.
