### ISSUE TITLE
调试过程中遇到的问题

### ISSUE THREAD

**Issue by tian984** [zhy0860/phi#3]
在调试过程中遇到了如下问题：
1   test.py文件中import dataset报错，dataset是您自定义的模块吗？
2   test.py文件中“parser.add_argument('--arch', type=str, default='kinetics_112se41', help='which architecture to use')”这个语句的含义是什么呢，default参数值如何获取呢？

望您解答，期待您的回复！

**Comment by zhy0860** [comment]
1 dataset是自定义的模块，dataset_ntusub.py和dataset_ntuview.py对应ntu60的两种划分，其他数据集请参考这两个程序修改即可
2 parser.add_argument('--arch', type=str, default='kinetics_112se41', help='which architecture to use')表示要测试的网络结构，参见genotypes.py中的不同网络结构

**Comment by tian984** [comment]
非常感谢您的耐心解答，这对我很重要

**Comment by zhy0860** [comment]
没关系，希望对您有帮助！
